name: Normal CI tests

on:
  push

jobs:
  build-n-publish:
    name: Continuous Integration Checks
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Install Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
    - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
      run: |
        # Upgrade pip
        python3 -m pip install --upgrade pip
        # Install build deps
        python3 -m pip install setuptools wheel twine
        # If requirements.txt exists, install from it
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install the package from setup.py
        python3 setup.py install

    # Tests with unittest
    - name: Test with unittest
      run: |
        cd tests
        python3 -m unittest discover
        cd ..